### PR TITLE
Added `adds` and `removes` events to collection

### PR DESCRIPTION
**Pull request by jameshartig**

### CODE REVIEW

**Comment by theabraham** [comment]
LGTM :8ball:

**Comment by fastest963** [comment]
Waiting for https://github.com/jashkenas/backbone/pull/3492 to verify they don't hate the event names or the changed `remove()` return behavior.

**Comment by fastest963** [comment]
Backbone devs decided against merging this into core but we're still going to go ahead and merge here. Just waiting on their thoughts on the return from `coll.remove`. I opened a new PR with just those changes.

**Comment by mc0** [comment]
I'm working on rewriting a few things, various improvements, removing some deprecated things and fixing some optimization issues. I'm planning on including this with the version increment. Right now it's tentatively in the branch dev-0.9.0.

**Comment by fastest963** [comment]
You gonna make a PR once its done?

**Comment by mc0** [comment]
Yep! I'll close this once I have a different pull request open.

**Pull request merged**
